services:
  database:
    build:
      dockerfile: ./docker/database/Dockerfile
      context: ./
    environment:
      - POSTGRES_PASSWORD=password
    env_file:
      - .env
    volumes:
      - api-data:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${APP_DB_NAME} -U ${APP_DB_USER}"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s
  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: ./
    env_file:
      - .env
    networks:
      - api-network
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      database:
        condition: service_healthy
volumes:
  api-data:
networks:
  api-network:
