name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: 'go-build'
      
      - name: Install dependencies
        run: go mod download
      
      - name: Run tests
        run: go test -v ./...